# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: Default
      demands:
      - agent.name -equals BMW-ZenBook-UX331FA-UX331FA
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerRegistryWass'
        repository: 'mwasssim211/currency-exchange-devops-v2'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
